### PR TITLE
Added 2 additional color schemes

### PR DESCRIPTION
**Pull request by RyanFitzgerald**
Added 2 additional color schemes keeping with the current layout and naming convention. 

First one being "Lime" which includes green colors and the second being "Banana" which includes yellow colors. Both color schemes also use flat colors.

### CODE REVIEW

**Comment by yigitozkavci** [comment]
I loved the names, they are cute! Can you post some screenshots for us to see what these new color schemes look like? :)

**Comment by RyanFitzgerald** [comment]
Not a problem! Here are the two themes:

Lime
lime-theme

Banana
banana-theme

**Comment by yigitozkavci** [comment]
Thanks dude, merging it. I'll update the [wiki](http://yigitozkavci.github.io/wowwizard/) to tell about new themes :)

**Comment by RyanFitzgerald** [comment]
Awesome! Love the project. I'll see where else I can help out.

**Pull request merged**
