### PR TITLE
align center to pokemon selection options in wow_wizard.css

### PR DESCRIPTION
**Pull request by atul-kumar02**

### CODE REVIEW

**Comment by yigitozkavci** [comment]
Hi, thank you for your interest. Please read `Contribution` part in README file, you need to edit files in `/dev`, and compile them to `css`.

Also, if you want to align them, can you please update the demo image in README? It's not centered as well.

**Comment by atul-kumar02** [comment]
I have updated reame.md in which I added center aligned image as well as wow_wizard.scss

**Review by yigitozkavci — CHANGES_REQUESTED** [review]
You should actually **build** your css file, not manually edit it. See `Contributing` on `README.md` for using gulp. After you build your css file, it looks nice and we can merge it :)

**Comment by yigitozkavci** [comment]
Any updates? @atul-kumar02

**Pull request closed without merging**
